### ISSUE TITLE
[ci] Sign APK for release in Github action

### ISSUE THREAD

**Issue by onuralpszr** [onuralpszr/CvCamera-Mobile#11]

**Comment by onuralpszr** [comment]
Complete via this commits c7dffe1cd216ff24f37606cb2f0cc39ffa88976d 2097d307fe341a1f6b99bd8b5aae767534e2ab87 e24a0dee635a66eb0c5126039116a4136b687c8c

**Comment by EmmanuelDav** [comment]
Hi @onuralpszr is this issue still available can I handle it?

**Comment by onuralpszr** [comment]
> Hi @onuralpszr is this issue still available can I handle it?

Sorry for late answer, sure you can do it :) Just make sure use secrets as well.
